/** Searchable subscription / recurring-service catalog (static knowledge base). */

export const CATALOG = [
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'Streaming',
    typicalPrice: 15.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.netflix.com',
    manageUrl: 'https://www.netflix.com/account',
    why: 'Huge catalog of shows and films if you watch several nights a week.',
    when: 'Worth it if you finish 2+ titles/month. Otherwise rotate in for a season.',
    how: 'Pick a plan → set a reminder on renew day → cancel from Account if idle.',
    tip: 'Standard with ads is cheaper for casual watching.',
    tags: ['video', 'movies', 'series']
  },
  {
    id: 'disney',
    name: 'Disney+',
    category: 'Streaming',
    typicalPrice: 8.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.disneyplus.com',
    manageUrl: 'https://www.disneyplus.com/account',
    why: 'Marvel, Star Wars, Pixar — great in bursts around big releases.',
    when: 'Subscribe when a show you care about drops; cancel after you finish.',
    how: 'Start monthly → binge → cancel before renew in account settings.',
    tip: 'Idle months are pure waste. Calendar the cancel-by date.',
    tags: ['video', 'marvel', 'kids']
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'Music',
    typicalPrice: 10.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.spotify.com',
    manageUrl: 'https://www.spotify.com/account',
    why: 'Daily music, podcasts, and offline downloads.',
    when: 'Keep if you listen most days. Skip if YouTube Music / Apple already covers you.',
    how: 'Check student/duo/family before paying full individual.',
    tip: 'Duo/family can cut per-person cost a lot.',
    tags: ['music', 'podcasts']
  },
  {
    id: 'applemusic',
    name: 'Apple Music',
    category: 'Music',
    typicalPrice: 10.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.apple.com/apple-music',
    manageUrl: 'https://support.apple.com/HT202039',
    why: 'Best if you live in Apple’s ecosystem and want lossless.',
    when: 'Choose one music service — don’t stack Spotify + Apple.',
    how: 'Manage from Apple ID subscriptions on iPhone.',
    tip: 'Student plan is half price if eligible.',
    tags: ['music', 'apple']
  },
  {
    id: 'ytpremium',
    name: 'YouTube Premium',
    category: 'Video',
    typicalPrice: 12.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.youtube.com/premium',
    manageUrl: 'https://www.youtube.com/paid_memberships',
    why: 'No ads + YouTube Music + background play.',
    when: 'Worth it if you watch a lot of YouTube or hate ads.',
    how: 'Start trial carefully — set cancel reminder before it ends.',
    tip: 'Family plan if 2+ people in household use it.',
    tags: ['video', 'music', 'ads']
  },
  {
    id: 'amazonprime',
    name: 'Amazon Prime',
    category: 'Shopping',
    typicalPrice: 8.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.amazon.com/prime',
    manageUrl: 'https://www.amazon.com/gp/primecentral',
    why: 'Shipping, Prime Video, and deals in one fee.',
    when: 'Keep only if you order enough that shipping savings beat the fee.',
    how: 'Check yearly vs monthly; cancel in Prime Central.',
    tip: 'Track orders for 2 months — if rare, cancel.',
    tags: ['shopping', 'video', 'shipping']
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT Plus',
    category: 'AI',
    typicalPrice: 20,
    currency: '€',
    cycle: 'monthly',
    url: 'https://chatgpt.com',
    manageUrl: 'https://chatgpt.com/#settings',
    why: 'Faster models and higher limits when you work/create a lot.',
    when: 'Pay in months you hit free limits weekly; pause when you don’t.',
    how: 'Easy to cancel in settings before renew.',
    tip: 'Compare with free Claude / Gemini before renewing every month.',
    tags: ['ai', 'productivity']
  },
  {
    id: 'claude',
    name: 'Claude Pro',
    category: 'AI',
    typicalPrice: 20,
    currency: '€',
    cycle: 'monthly',
    url: 'https://claude.ai',
    manageUrl: 'https://claude.ai/settings',
    why: 'Strong for long writing and coding chats.',
    when: 'Only if you outgrow free usage regularly.',
    how: 'Subscribe → use hard for a month → cancel if quiet.',
    tip: 'Don’t stack with ChatGPT Plus unless both are daily tools.',
    tags: ['ai', 'writing']
  },
  {
    id: 'adobe',
    name: 'Adobe Creative Cloud',
    category: 'Software',
    typicalPrice: 59.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.adobe.com/creativecloud.html',
    manageUrl: 'https://account.adobe.com/plans',
    why: 'Full design/video suite for people who ship creative work weekly.',
    when: 'Overkill for light edits — Photo plan is enough for many.',
    how: 'Cancel or downgrade in Adobe account ≥24h before renew.',
    tip: 'Photography plan (~€12) often replaces the full suite.',
    tags: ['design', 'photo', 'video']
  },
  {
    id: 'microsoft365',
    name: 'Microsoft 365',
    category: 'Software',
    typicalPrice: 7,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.microsoft.com/microsoft-365',
    manageUrl: 'https://account.microsoft.com/services',
    why: 'Word/Excel/OneDrive if school or work needs Office files.',
    when: 'Skip if Google Docs + free OneDrive is enough.',
    how: 'Family plan can cover a household cheaper per person.',
    tip: 'Annual billing usually cheaper than monthly.',
    tags: ['office', 'cloud']
  },
  {
    id: 'icloud',
    name: 'iCloud+',
    category: 'Storage',
    typicalPrice: 2.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.apple.com/icloud',
    manageUrl: 'https://support.apple.com/HT202039',
    why: 'Photo backup and device sync for iPhone users.',
    when: '200GB is the sweet spot for most people.',
    how: 'Change plan in iPhone Settings → Apple ID → iCloud.',
    tip: 'Clear old backups before jumping to 2TB.',
    tags: ['apple', 'backup', 'storage']
  },
  {
    id: 'googleone',
    name: 'Google One',
    category: 'Storage',
    typicalPrice: 1.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://one.google.com',
    manageUrl: 'https://one.google.com/storage',
    why: 'Extra Drive / Photos storage across Android & web.',
    when: 'Needed once free 15GB fills up.',
    how: 'Upgrade only one step at a time; cancel anytime in Google One.',
    tip: 'Compress Photos backup to delay paying.',
    tags: ['google', 'storage']
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'Productivity',
    typicalPrice: 10,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.notion.so',
    manageUrl: 'https://www.notion.so/my-account',
    why: 'Notes, wikis, and light project tracking in one place.',
    when: 'Free plan is enough for solo notes; Plus for AI/files.',
    how: 'Try free first for 2 weeks before paying.',
    tip: 'Don’t pay for AI add-ons you won’t open daily.',
    tags: ['notes', 'productivity']
  },
  {
    id: 'canva',
    name: 'Canva Pro',
    category: 'Design',
    typicalPrice: 12.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.canva.com',
    manageUrl: 'https://www.canva.com/settings/billing-and-teams',
    why: 'Fast graphics for social, school, and side projects.',
    when: 'Pro matters for brand kit, background remover, premium stock.',
    how: 'Use free → upgrade for a project month → cancel after.',
    tip: 'Annual is cheaper if you design every week.',
    tags: ['design', 'social']
  },
  {
    id: 'github',
    name: 'GitHub Pro',
    category: 'Dev',
    typicalPrice: 4,
    currency: '€',
    cycle: 'monthly',
    url: 'https://github.com/pricing',
    manageUrl: 'https://github.com/settings/billing',
    why: 'Advanced features for private repos and insights.',
    when: 'Most indie devs are fine on free.',
    how: 'Only upgrade when free limits block you.',
    tip: 'Students get Pro free via GitHub Education.',
    tags: ['dev', 'code']
  },
  {
    id: 'xbox',
    name: 'Xbox Game Pass Core/Ultimate',
    category: 'Gaming',
    typicalPrice: 12.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.xbox.com/game-pass',
    manageUrl: 'https://account.microsoft.com/services',
    why: 'Huge game library if you play several titles a month.',
    when: 'Cancel in quiet months; resubscribe when a big drop hits.',
    how: 'Manage in Microsoft account subscriptions.',
    tip: 'Stacking Ultimate + buying full games can double-spend.',
    tags: ['games', 'xbox']
  },
  {
    id: 'psplus',
    name: 'PlayStation Plus',
    category: 'Gaming',
    typicalPrice: 13.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.playstation.com/ps-plus',
    manageUrl: 'https://www.playstation.com/acct/subscriptions',
    why: 'Online multiplayer + monthly games + catalog on higher tiers.',
    when: 'Essential for PS online play; Extra/Premium only if you use the catalog.',
    how: 'Prefer yearly when on sale; cancel monthly if inactive.',
    tip: 'Don’t pay Premium if you only need multiplayer.',
    tags: ['games', 'playstation']
  },
  {
    id: 'nintendo',
    name: 'Nintendo Switch Online',
    category: 'Gaming',
    typicalPrice: 3.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.nintendo.com/switch/online',
    manageUrl: 'https://ec.nintendo.com',
    why: 'Online play + classic games for Switch.',
    when: 'Cheap — keep if you play online at all.',
    how: 'Family plan is great value for households.',
    tip: 'Yearly plan is much cheaper than monthly.',
    tags: ['games', 'nintendo']
  },
  {
    id: 'gym',
    name: 'Gym membership',
    category: 'Health',
    typicalPrice: 39,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.google.com/search?q=gym+near+me',
    manageUrl: '',
    why: 'Equipment and classes if you show up 8+ times/month.',
    when: 'Under ~6 visits/month, day passes often win.',
    how: 'Read cancel notice (often 30 days). Put cancel date in calendar.',
    tip: 'Ask for freeze instead of cancel if you’ll return soon.',
    tags: ['fitness', 'health']
  },
  {
    id: 'duolingo',
    name: 'Duolingo Super',
    category: 'Learning',
    typicalPrice: 6.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.duolingo.com',
    manageUrl: 'https://www.duolingo.com/settings/superduolingo',
    why: 'No hearts + offline — helpful for daily streaks.',
    when: 'Free is fine for light practice; Super if hearts block you.',
    how: 'Family plan if multiple learners.',
    tip: 'Annual sale pricing is common around New Year.',
    tags: ['language', 'education']
  },
  {
    id: 'skillshare',
    name: 'Skillshare',
    category: 'Learning',
    typicalPrice: 13.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.skillshare.com',
    manageUrl: 'https://www.skillshare.com/en/settings/billing',
    why: 'Creative classes for design, video, business hobbies.',
    when: 'Pay for a focused learning month, then pause.',
    how: 'Cancel before renew if you’re not taking classes.',
    tip: 'Don’t keep it “just in case.”',
    tags: ['education', 'creative']
  },
  {
    id: 'dropbox',
    name: 'Dropbox Plus',
    category: 'Storage',
    typicalPrice: 11.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.dropbox.com',
    manageUrl: 'https://www.dropbox.com/account/plan',
    why: 'File sync across devices and sharing.',
    when: 'Skip if Google Drive / OneDrive / iCloud already covers you.',
    how: 'Avoid stacking multiple cloud storages.',
    tip: 'One cloud paid plan is enough for most people.',
    tags: ['storage', 'files']
  },
  {
    id: 'nordvpn',
    name: 'NordVPN',
    category: 'Security',
    typicalPrice: 12.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://nordvpn.com',
    manageUrl: 'https://my.nordaccount.com',
    why: 'Privacy on public Wi‑Fi and some geo content.',
    when: 'Useful for travel / sensitive work; optional at home.',
    how: 'Long-term plans are cheaper; monthly is flexible.',
    tip: 'One VPN is enough — don’t stack.',
    tags: ['vpn', 'security']
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden Premium',
    category: 'Security',
    typicalPrice: 1,
    currency: '€',
    cycle: 'monthly',
    url: 'https://bitwarden.com',
    manageUrl: 'https://vault.bitwarden.com/#/settings/subscription',
    why: 'Password manager with 2FA and emergency access.',
    when: 'Premium is cheap and worth it over browser-only saves.',
    how: 'Free works; Premium adds TOTP and more storage.',
    tip: 'One of the highest value €1 tools you can buy.',
    tags: ['passwords', 'security']
  },
  {
    id: 'twitch',
    name: 'Twitch Turbo / Subs',
    category: 'Entertainment',
    typicalPrice: 5.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.twitch.tv',
    manageUrl: 'https://www.twitch.tv/subscriptions',
    why: 'Support creators + ad-free / emotes depending on product.',
    when: 'Channel subs are intentional gifts; Turbo only if you live on Twitch.',
    how: 'Review recurring channel subs monthly — they stack silently.',
    tip: 'Audit gifts/subs every payday.',
    tags: ['streaming', 'twitch']
  },
  {
    id: 'patreon',
    name: 'Patreon memberships',
    category: 'Creators',
    typicalPrice: 5,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.patreon.com',
    manageUrl: 'https://www.patreon.com/settings/memberships',
    why: 'Support creators you actually follow.',
    when: 'Keep only active pledges you still open.',
    how: 'Open memberships page monthly and cut silent pledges.',
    tip: 'Treat each pledge like a mini-sub.',
    tags: ['creators', 'membership']
  },
  {
    id: 'chatgpt_team',
    name: 'Cursor / AI coding sub',
    category: 'Dev',
    typicalPrice: 20,
    currency: '€',
    cycle: 'monthly',
    url: 'https://cursor.com',
    manageUrl: 'https://cursor.com/settings',
    why: 'Speeds coding if you ship software often.',
    when: 'Worth it in heavy build months; pause in downtime.',
    how: 'Track whether it saves real hours weekly.',
    tip: 'One AI coding tool is usually enough.',
    tags: ['dev', 'ai']
  },
  {
    id: 'hbo',
    name: 'Max (HBO)',
    category: 'Streaming',
    typicalPrice: 9.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.max.com',
    manageUrl: 'https://auth.max.com',
    why: 'Premium series if you watch prestige TV.',
    when: 'Rotate with Netflix/Disney — don’t run all three forever.',
    how: 'Subscribe for a show run, then cancel.',
    tip: 'Share a plan only if the household rules allow it.',
    tags: ['video', 'series']
  },
  {
    id: 'paramount',
    name: 'Paramount+',
    category: 'Streaming',
    typicalPrice: 7.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.paramountplus.com',
    manageUrl: 'https://www.paramountplus.com/account',
    why: 'Sports / specific shows depending on region.',
    when: 'Only while that content matters to you.',
    how: 'Monthly on/off around seasons.',
    tip: 'Check if a mobile carrier already bundles it.',
    tags: ['video', 'sports']
  },
  {
    id: 'linkedin',
    name: 'LinkedIn Premium',
    category: 'Career',
    typicalPrice: 29.99,
    currency: '€',
    cycle: 'monthly',
    url: 'https://www.linkedin.com/premium',
    manageUrl: 'https://www.linkedin.com/mypreferences/d/premium-manage',
    why: 'InMail and insights while job hunting.',
    when: 'Use for active job search months only.',
    how: 'Start when applying hard; cancel when settled.',
    tip: 'One of the easiest subs to forget — set a 30-day reminder.',
    tags: ['jobs', 'career']
  }
];

export const CATEGORIES = [
  'All',
  'Streaming',
  'Music',
  'Video',
  'AI',
  'Software',
  'Storage',
  'Productivity',
  'Design',
  'Dev',
  'Gaming',
  'Health',
  'Learning',
  'Security',
  'Shopping',
  'Entertainment',
  'Creators',
  'Career'
];

export function catalogById(id) {
  return CATALOG.find((c) => c.id === id) || null;
}

export function searchCatalog(query, category = 'All') {
  const q = String(query || '').trim().toLowerCase();
  return CATALOG.filter((c) => {
    if (category !== 'All' && c.category !== category) return false;
    if (!q) return true;
    const hay = `${c.name} ${c.category} ${(c.tags || []).join(' ')} ${c.why}`.toLowerCase();
    return hay.includes(q);
  });
}
